[package]
name = "sl-mod-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
reqwest = { version = "0.12.14", features = ["blocking", "json"]}
urlencoding = "2.1.2" 